[package]
name = "file_yeet_server"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.18", features = ["derive"] }
faster-hex = "0.9.0"
file_yeet_shared = { path = "../shared" }
futures-util = "0.3.30"
tokio = { version = "1.35.1", features = ["full"] }
warp = { version="0.3.6", features = ["tls"] }